################################################################################
# Copyright (c) 2017, Lawrence Livermore National Security, LLC.
# Produced at the Lawrence Livermore National Laboratory.
#
# Written by Huu Tan Nguyen <htpnguyen@ucdavis.edu>.
#
# LLNL-CODE-740862. All rights reserved.
#
# This file is part of CallFlow. For details, see:
# https://github.com/LLNL/CallFlow
# Please also read the LICENSE file for the MIT License notice.
################################################################################

#!/bin/bash

# Given the output of HPC Toolkit generate a folder with all the required callflow data
# Args : $1 (path)  folder containing the HPCToolkit data, 
#                   must have the xml and the combined mdb  
#                   automatically generated by hpcviewer when plotting any histogram
#
#        $2 (name)  name for the data folder and json file where callflow data will be generated
#        $3 (int)   number of nodes where the experiment was run (srun -N nodes) 

node dataParser.js $1
mkdir $2 
cp $1/nodeData.json $2
cp $1/experiment.xml $2

cat << EOF >> $2.json 
{
	"dataName" : "$2",
	"numbNodes" : "$3",
	"path" : "`pwd`/$2/",
	"experiment" : "experiment.xml",
	"nodeMetric" : "nodeData.json",
	"port" : 8900
}

EOF
